CREATE TABLE HELP(
	index_help int,
	nr_wierzcholka int
);

CREATE TABLE KRAWEDZIE(
	wierzcholek1 int,
	wierzcholek2 int
);

INSERT INTO KRAWEDZIE VALUES(1,3);
INSERT INTO KRAWEDZIE VALUES(2,3);
INSERT INTO KRAWEDZIE VALUES(3,4);
INSERT INTO KRAWEDZIE VALUES(4,5);
INSERT INTO KRAWEDZIE VALUES(5,3);
INSERT INTO KRAWEDZIE VALUES(3,5);

CREATE TABLE WIERZCHOLKI(
	wierzcholek int
);

INSERT INTO WIERZCHOLKI VALUES(1);
INSERT INTO WIERZCHOLKI VALUES(2);
INSERT INTO WIERZCHOLKI VALUES(3);
INSERT INTO WIERZCHOLKI VALUES(4);
INSERT INTO WIERZCHOLKI VALUES(5);


CREATE TABLE MACIERZ(
	row_m int,
	col_m int,
	value_m int
);

INSERT INTO MACIERZ VALUES(1,1,null);
INSERT INTO MACIERZ VALUES(1,2,0);
INSERT INTO MACIERZ VALUES(1,3,1);
INSERT INTO MACIERZ VALUES(1,4,0);
INSERT INTO MACIERZ VALUES(1,5,0);

INSERT INTO MACIERZ VALUES(2,1,0);
INSERT INTO MACIERZ VALUES(2,2,null);
INSERT INTO MACIERZ VALUES(2,3,1);
INSERT INTO MACIERZ VALUES(2,4,0);
INSERT INTO MACIERZ VALUES(2,5,0);

INSERT INTO MACIERZ VALUES(3,1,0);
INSERT INTO MACIERZ VALUES(3,2,0);
INSERT INTO MACIERZ VALUES(3,3,null);
INSERT INTO MACIERZ VALUES(3,4,1);
INSERT INTO MACIERZ VALUES(3,5,1);

INSERT INTO MACIERZ VALUES(4,1,0);
INSERT INTO MACIERZ VALUES(4,2,0);
INSERT INTO MACIERZ VALUES(4,3,0);
INSERT INTO MACIERZ VALUES(4,4,null);
INSERT INTO MACIERZ VALUES(4,5,1);

INSERT INTO MACIERZ VALUES(5,1,0);
INSERT INTO MACIERZ VALUES(5,2,0);
INSERT INTO MACIERZ VALUES(5,3,1);
INSERT INTO MACIERZ VALUES(5,4,0);
INSERT INTO MACIERZ VALUES(5,5,null);

CREATE TABLE TYPY(
	nr_typu int,
	suma int
);

INSERT INTO TYPY VALUES(1,12);
INSERT INTO TYPY VALUES(2,36);
INSERT INTO TYPY VALUES(3,44);
INSERT INTO TYPY VALUES(4,20);
INSERT INTO TYPY VALUES(5,28);

INSERT INTO TYPY VALUES(6,60);
INSERT INTO TYPY VALUES(7,41);
INSERT INTO TYPY VALUES(8,45);
INSERT INTO TYPY VALUES(9,25);
INSERT INTO TYPY VALUES(10,29);

INSERT INTO TYPY VALUES(11,53);
INSERT INTO TYPY VALUES(12,61);
INSERT INTO TYPY VALUES(13,63);


CREATE TABLE WYNIK(
	w1 int,
	w2 int,
	w3 int,
	typ int
);